import Head from "next/head";
import Layout from "../components/Layout";
import Homepage from "../components/Homepage";
import Services from "../components/Services";
import css from "../styles/Home.module.css";
import { client } from "../lib/client";

export default function Home({noodles}) {
  console.log(noodles);   
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>NOODLES EXPRESS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <Homepage/> 
          <Services/>   
        </main>
      </div>
    </Layout>
  );
}

export const getServerSideProps = async() => {
  const query = '*[_type == "noodles"]';
  const noodles = await client.fetch(query);
  return {
    props:{
      noodles 
    }
  }
}